export const CHANGE_SINGER_LIST = 'CHANGE_SINGER_LIST';
export const CHANGE_PAGE_COUNT = 'CHANGE_PAGE_COUNT';
export const CHANGE_ENTER_LOADING = 'CHANGE_ENTER_LOADING';
export const CHANGE_PULLUP_LOADING = 'CHANGE_PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'CHANGE_PULLDOWN_LOADING';